apiVersion: template.openshift.io/v1
kind: Template
metadata:
  labels:
    app: foi-help
  name: backend-build
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: backend
    labels:
      app: foi-help
- apiVersion: v1
  kind: BuildConfig
  metadata:
    name: backend-build
    labels:
      app: foi-help
      name: backend-build
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: backend:latest
    # resources:
    #   limits:
    #     cpu: 2
    #     memory: 2Gi
    #   requests:
    #     cpu: 2
    #     memory: 1Gi
    runPolicy: Serial
    source:
      contextDir: backend
      git:
        ref: main
        uri: https://github.com/bcgov/foi-help.git
      type: Git
    strategy:
      sourceStrategy:
        env:
        - name: BUILD_LOGLEVEL
          value: "5"
        from:
          kind: ImageStreamTag
          name: nodejs:14-ubi8
          namespace: openshift
        incremental: false
      type: Source
    triggers:
    - type: ConfigChange