---
kind: Template
apiVersion: v1
metadata:
  annotations:
    description: Deployment template for a adjudication api service.
    tags: "${API_NAME}"
  name: "${API_NAME}-deploy"
objects:
- kind: DeploymentConfig
  apiVersion: v1
  metadata:
    name: "${API_NAME}"
    labels:
      app: "${API_NAME}"
      app-group: "${APP_GROUP}"
      template: "${API_NAME}-deploy"
  spec:
    strategy:
      type: Rolling
      rollingParams:
        updatePeriodSeconds: 1
        intervalSeconds: 1
        timeoutSeconds: 600
        maxUnavailable: 25%
        maxSurge: 25%
        # pre:
        #   failurePolicy: Abort
          # execNewPod:
            # command:
            # - "/bin/bash"
            # - "-c"
            # - "python manage.py db upgrade"
            # containerName: "${API_NAME}"
    triggers:
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
        - "${API_NAME}"
        from:
          kind: ImageStreamTag
          namespace: "${IMAGE_NAMESPACE}"
          name: "${API_NAME}:${TAG_NAME}"
    - type: ConfigChange
    replicas: 1
    test: false
    selector:
      app: "${API_NAME}"
      deploymentconfig: "${API_NAME}"
    template:
      metadata:
        labels:
          app: "${API_NAME}"
          app-group: "${APP_GROUP}"
          deploymentconfig: "${API_NAME}"
          template: "${API_NAME}-deploy"
          role: api
      spec:
        containers:
        - name: "${API_NAME}"
          image: "${API_NAME}"
          imagePullPolicy: Always
          ports:
          - containerPort: 1337
            protocol: TCP
          env:
            - name: FOI_DATABASE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: "${DB_SECRETS}"
                  key: database-user
            - name: FOI_DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: "${DB_SECRETS}"
                  key: database-password
            - name: FOI_DATABASE_NAME
              valueFrom:
                secretKeyRef:
                  name: "${DB_SECRETS}"
                  key: database-name
            # Assuming DB_SECRETS is like "postgresql" and hostname matches secret name
            - name: FOI_DATABASE_HOST
              value: "${DB_SECRETS}"
            - name: FOI_DATABASE_PORT
              value: "5432"
            # - name: APP_KEYS
            #   valueFrom:
            #     secretKeyRef:
            #       name: "backend-secrets"
            #       key: APP_KEYS
          envFrom:
            - secretRef:
                name: backend-secrets
          # resources:
          #   requests:
          #     cpu: "50m"
          #     memory: "250Mi"
          #   limits:
          #     cpu: "150m"
          #     memory: "500Mi"
          # readinessProbe:
          #   httpGet:
          #     path: /_health
          #     port: 1337
          #     scheme: HTTP
          #   initialDelaySeconds: 60
          #   timeoutSeconds: 3
          #   periodSeconds: 60
          #   successThreshold: 1
          #   failureThreshold: 3          
          terminationMessagePath: "/dev/termination-log"
          terminationMessagePolicy: File
          imagePullPolicy: Always
        restartPolicy: Always
        terminationGracePeriodSeconds: 30
        dnsPolicy: ClusterFirst
        securityContext: {}
        schedulerName: default-scheduler
- kind: Service
  apiVersion: v1
  metadata:
    name: "${API_NAME}"
    creationTimestamp: 
    labels:
      app: "${API_NAME}"
      app-group: "${APP_GROUP}"
      template: "${API_NAME}-deploy"
  spec:
    ports:
    - name: 1337-tcp
      protocol: TCP
      port: 1337
      targetPort: 1337
    selector:
      deploymentconfig: "${API_NAME}"
    type: ClusterIP
    sessionAffinity: None
  # status:
  #   loadBalancer: {}
- kind: Route
  apiVersion: v1
  metadata:
    name: "${API_NAME}"
    labels:
      app: "${API_NAME}"
      app-group: "${APP_GROUP}"
      template: "${API_NAME}-deploy"
  spec:
    to:
      kind: Service
      name: "${API_NAME}"
      weight: 100
    port:
      targetPort: 1337-tcp
    tls:
      termination: edge
    wildcardPolicy: None
    host: "${APP_GROUP}-${API_NAME}-${TAG_NAME}.apps.silver.devops.gov.bc.ca"
parameters:
- name: API_NAME
  displayName: Name
  description: The name assigned to all of the OpenShift resources associated to the
    server instance.
  required: true
  value: backend
- name: APP_GROUP
  displayName: App Group
  description: The name assigned to all of the deployments in this project.
  required: true
  value: foi-help
- name: IMAGE_NAMESPACE
  displayName: Image Namespace
  required: true
  description: The namespace of the OpenShift project containing the imagestream for
    the application.
  value: eeced3-tools
- name: TAG_NAME
  displayName: Environment TAG name
  description: The TAG name for this environment, e.g., dev, test, prod
  required: true
  value: dev
- name: DB_SECRETS
  displayName: Environment TAG name
  description: The TAG name for this environment, e.g., dev, test, prod
  required: true
  value: postgresql
