name: Backend Deploy


on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: Target environment to deploy latest changes
        default: "dev"
        required: true
        options:
        - dev
        - test
        - prod

defaults:
  run:
    shell: bash
    working-directory: ./backend

env:
  APP_NAME: "backend-build"
  TAG_NAME: "dev"

jobs:
  backend-build-cd-by-push:
    runs-on: ubuntu-20.04

    if: github.repository == 'bcgov/foi-help'
    environment:
      name: "dev"

    steps:
      - uses: actions/checkout@v2

      - name: start
        run: | 
          echo "Building and deploying for ${{ github.event.inputs.environment }}"

      - name: Login Openshift
        shell: bash
        run: |
          oc login --server=${{secrets.OPENSHIFT4_LOGIN_REGISTRY}} --token=${{secrets.OPENSHIFT4_SA_TOKEN}}

      - name: Tools project
        shell: bash
        run: |
          oc project ${{ secrets.OPENSHIFT4_FRONTEND_REPOSITORY }}-tools

      - name: Start Build Openshift
        shell: bash
        run: |
          oc start-build ${{ env.APP_NAME }} --wait

      - name: Tools project
        shell: bash
        run: |
          oc tag ${{ env.APP_NAME }}:latest ${{ env.APP_NAME }}:${{ github.event.inputs.environment }} 

      # - name: Rocket.Chat Notification
      #   uses: RocketChat/Rocket.Chat.GitHub.Action.Notification@master
      #   if: failure()
      #   with:
      #     type: ${{ job.status }}
      #     job_name: "*Auth Web Built and Deployed to ${{env.TAG_NAME}}*"
      #     channel: "#registries-bot"
      #     url: ${{ secrets.ROCKETCHAT_WEBHOOK }}
      #     commit: true
      #     token: ${{ secrets.GITHUB_TOKEN }}
